version: '3.8'
services:
  db:
    image: postgres:14
    container_name: db-1
    environment:
      POSTGRES_DB: db-1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: development_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: