[build]
  base = "frontend"
  command = "node --version && npm --version && npm ci && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.17.0"
  # NPM_FLAGS removed - using npm ci for deterministic installs
  NETLIFY_USE_YARN = "false"
  # Allow Netlify caching for faster builds
  # NETLIFY_SKIP_CACHE = "true"
  # Demo mode set to true to use mock data instead of real API
  REACT_APP_USE_DEMO_MODE = "true"
  # Show more build output
  CI = "false"

# Cache settings for better performance
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200