[build]
  base = "frontend"
  command = "rm -rf node_modules package-lock.json && npm cache clean --force && npm install --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_FLAGS = "--legacy-peer-deps"
  # Demo mode set to true to use mock data instead of real API
  REACT_APP_USE_DEMO_MODE = "true"

# Cache settings for better performance
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200