[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "18"
  # Demo mode set to true to use mock data instead of real API
  REACT_APP_USE_DEMO_MODE = "true"

# Cache settings for better performance
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200